--PERMISOS ROL ADMINISTRADOR
GRANT SELECT, INSERT, UPDATE, DELETE ON Cliente TO RolAdministrador;
GRANT SELECT, INSERT, UPDATE, DELETE ON Usuario TO RolAdministrador;
GRANT SELECT, INSERT, UPDATE, DELETE ON ArticuloEquipo TO RolAdministrador;
GRANT SELECT, INSERT, UPDATE, DELETE ON OrdenDiagnostico TO RolAdministrador;
GO